[package]
name = "netredirect-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
detours-sys = "0.1.1"
winapi = { version = "0.3", features = ["winsock2", "processthreadsapi"] }
lazy_static = "1.4"

[build-dependencies]
cc = "1.0"
